### ISSUE TITLE
final_model a zip archive?

### ISSUE THREAD

**Issue by QUEST2179** [brennanaba/ABlooper#2]
Could you please help with this issue? Thanks!

Traceback (most recent call last):
  File "testABlooper.py", line 5, in <module>
    from ABlooper import CDR_Predictor
  File "C:\Users\18482\work\ABlooper-master\ABlooper\__init__.py", line 1, in <module>
    from ABlooper.ABlooper import CDR_Predictor
  File "C:\Users\18482\work\ABlooper-master\ABlooper\ABlooper.py", line 13, in <module>
    default_model.load_state_dict(torch.load(path, map_location=torch.device(device)))
  File "C:\Users\18482\miniconda3\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\18482\miniconda3\lib\site-packages\torch\serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: C:\Users\18482\work\ABlooper-master\ABlooper\trained_model\final_model is a zip archive (did you mean to use torch.jit.load()?)

**Comment by brennanaba** [comment]
Hi QUEST,

Sorry, but I am not able to reproduce your issue. From a quick Google, it seems to be related to using a PyTorch version more recent than 1.6.0 ([link](https://github.com/pytorch/pytorch/issues/43766)).

If you could please tell me your Python version, PyTorch version and operating system I will see how I can help.

All the best,

Brennan

**Comment by brennanaba** [comment]
Closed as the issue appears to be related to different versions of PyTorch. 

I would be happy to help if QUEST gives more details.
